:doctype: book
// The top-level file that describes the book's composition
:booklet-theme-phrase: One is greater than zero

= {booklet-theme-phrase}: A Daily Schedule
Silas Waxter

// default image location is project root
:imagesdir: ..
// Attributes used as interface to build system. Pass a generalized prefix and
// suffix for each day of the week. The filename is abstracted except for the
// day identifier like 'monday' or 'tuesday.
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]
image::{day-pdf-prefix}day{day-pdf-suffix}[pages=1..2]

:backlog-type: Shopping
:include-location: //defined
include::backlogs/basic.adoc[]

:backlog-type: Chores
:include-location: //defined
include::backlogs/basic.adoc[]

:note-type: Misc for Digital Transfer
include::notes/basic.adoc[]

:note-type: Content to Consume/Research
include::notes/basic.adoc[]

// blank page for inserting into wallet (solves #5)
<<<
{sp}

